### ISSUE TITLE
NameError: uninitialized constant MiniTest in Minitest > 5.18.1

### ISSUE THREAD

**Issue by schinery** [ordinaryzelig/minispec-metadata#20]
The release of Minitest 5.19.0 removed using `MiniTest` (see [here](https://github.com/minitest/minitest/issues/960)) so now any gems using this and not `Minitest` break, including this one.

```sh
NameError: uninitialized constant MiniTest
/vendor/bundle/ruby/3.2.0/gems/minispec-metadata-2.0.0/lib/core_extensions.rb:3:in `<main>'
/vendor/bundle/ruby/3.2.0/gems/minispec-metadata-2.0.0/lib/minispec-metadata.rb:2:in `require_relative'
/vendor/bundle/ruby/3.2.0/gems/minispec-metadata-2.0.0/lib/minispec-metadata.rb:2:in `<main>'
```

**Comment by schinery** [comment]
Ignore this. Another gem is pinned to an older version andminispec-metadata is all good.
