### ISSUE TITLE
undefined method `metadata_for_test_name' 

### ISSUE THREAD

**Issue by dogweather** [ordinaryzelig/minispec-metadata#9]
I'm not sure what the problem is:

```
01:39:15 - INFO - Run all
01:39:15 - INFO - Running: all tests
Run options: --tag ~slow --seed 50604

# Running:

/Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:61:in `block in runnable_method_matches_any_tags?': undefined method `metadata_for_test_name' for #<Class:0x007fc4f13e9dc0> (NoMethodError)
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:60:in `any?'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:60:in `runnable_method_matches_any_tags?'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:54:in `runnable_method_matches_any_exclusive_tag?'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:43:in `block in runnable_methods'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:42:in `reject'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minispec-metadata-3.2.0/lib/minispec-metadata/tags.rb:42:in `runnable_methods'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minitest-5.5.1/lib/minitest.rb:283:in `run'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minitest-5.5.1/lib/minitest.rb:150:in `block in __run'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minitest-5.5.1/lib/minitest.rb:150:in `map'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minitest-5.5.1/lib/minitest.rb:150:in `__run'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minitest-5.5.1/lib/minitest.rb:127:in `run'
    from /Users/robb/.rvm/gems/ruby-2.2.0/gems/minitest-5.5.1/lib/minitest.rb:56:in `block in autorun'
```

**Comment by ordinaryzelig** [comment]
Has it worked for you before on this version? Does it work without the tag option? If you could give me some self-contained, reproducible code, it would help me to diagnose.

First suspicion is that it may not be behaving on ruby 2.2.0. I haven't tried that version yet.

Give me some time and I'll get back to this.

**Comment by dogweather** [comment]
This is the first time I've tried using it. I'll test with ruby 2.1.

**Comment by roychoo** [comment]
i had also encounter this error, for me it was due that one of the minitests is not minispec

**Comment by ordinaryzelig** [comment]
> i had also encounter this error, for me it was due that one of the minitests is not minispec

Ah, thanks for the hint. I still have not run into this issue yet myself, but I'll be on the lookout for that.
